<?php

namespace RBSoft\CartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenRepository extends EntityRepository
{
}
