<?php

namespace RBSoft\CartBundle\Repository;

/**
 * FleteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FleteRepository extends \Doctrine\ORM\EntityRepository
{
}
