<?php

namespace RBSoft\CartBundle\Repository;

/**
 * OrdenEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
