<?php

namespace RBSoft\CartBundle\Repository;
use RBSoft\UsuarioBundle\Entity\Usuario;

/**
 * OrdenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenRepository extends \Doctrine\ORM\EntityRepository
{

    public function getComprasPendientesByUser(Usuario $usuario)
    {
        $qb = $this->createQueryBuilder('o')
            ->join('o.estado','e','WITH','e.estado = 0','o.id')
            ->where('o.cliente = :cliente')
            ->setParameter('cliente', $usuario->getId());

        return $qb->getQuery()->getResult();

    }

}
