<?php

namespace RBSoft\CartBundle\Repository;

/**
 * OrdenDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
