<?php

namespace RBSoft\UtilidadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProvinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinciaRepository extends EntityRepository
{
    public function findByPaisId($pais_id)
    {
        $query = $this->getEntityManager()->createQuery("
                SELECT provincia
                FROM UtilidadBundle:Provincia provincia
                LEFT JOIN provincia.pais pais
                WHERE pais.id = :pais_id
        ")->setParameter('pais_id', $pais_id);
        return $query->getArrayResult();
    }
}
