# Assetic Configuration

assetic:
    debug: '%kernel.debug%'
    use_controller: true
    bundles: [ AppBundle, UsuarioBundle ]
    java: '%java_path%'
    filters:
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        cssrewrite: ~
        lessphp:
            apply_to:          "\\.less$"
            file:              '%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php'
            formatter:         "compressed"
            preserve_comments: false

    assets:
        lesses:
            inputs:
#                - %kernel.root_dir%/../web/assets/bootstrap-2.3.2/less/bootstrap.less
#                - @BricksSiteBundle/Resources/less/*.less
#                - @BricksWikiBundle/Resources/less/*.less
#                - @BricksUserBundle/Resources/less/*.less
#                - @BricksMessageBundle/Resources/less/*.less
            filters: lessphp
        stylesheets_frontend:
            inputs:
                #-- App CSS --#>
                - bundles/app/css/frontend/main.css
                - bundles/app/css/frontend/style.css
                - bundles/app/css/frontend/responsive.css

            filters:
                - cssrewrite
#                - ?yui_css
        stylesheets_admin:
            inputs:
                #-- Font Awesome CSS --#
                - assets/css/font-awesome.min.css
                #-- Bootstrap CSS --#
                - assets/css/bootstrap.min.css

                - bundles/rbsoftabmgenerador/fileupload/css/fileinput.min.css
                - assets/js/plugins/magnific/magnific-popup.css
                - assets/js/plugins/bootstrap-datepicker/datepicker3.css

                #-- App CSS --#>
                - bundles/app/css/admin/mvpready-admin.css

            filters:
                - cssrewrite
#                - ?yui_css
        javascripts_header:
            inputs:
                - bundles/fosjsrouting/js/router.js
                - bundles/app/js/frontend/ajaxTool.js
                - bundles/app/js/frontend/frontend.js

            filters:
                - cssrewrite
#                - ?yui_js
        javascripts_footer_admin:
            inputs:
                #-- Bootstrap core JavaScript
                #-- Core JS --#

                - assets/js/libs/bootstrap.min.js
                - assets/js/plugins/jquery-ui-1.11.4.custom/jquery-ui.min.js
#                Este lo sacamos de aqui porque el assetic modifica el path, es un error.
#                - bundles/rbsoftabmgenerador/fileupload//js/fileinput.js
                ##-- Plugin JS --##
                - assets/js/libs/jquery.form.min.js
                - assets/js/plugins/moment/moment.min.js
                - assets/js/plugins/moment/moment-with-locales.min.js

#                <script src="{{ asset('assets/js/plugins/flot/jquery.flot.js') }} "></script>
#                <script src="{{ asset('assets/js/plugins/flot/jquery.flot.tooltip.min.js') }} "></script>
#                <script src="{{ asset('assets./js/plugins/flot/jquery.flot.pie.js') }} "></script>
#                <script src="{{ asset('assets/js/plugins/flot/jquery.flot.resize.js') }} "></script>

                - assets/js/plugins/magnific/jquery.magnific-popup.min.js
                - assets/js/plugins/bootstrap-datepicker/bootstrap-datepicker.js
                - assets/js/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.es.js
                - assets/js/plugins/jquery.autosize/jquery.autosize.js
                - assets/js/plugins/jquery-sortable/jquery-sortable.js


                ##-- App JS --##
                - bundles/app/js/admin/mvpready-core.js
                - bundles/app/js/admin/mvpready-admin.js

        javascripts_footer_frontend:
            inputs:
                #-- Bootstrap core JavaScript
                #-- Core JS --#

                - assets/js/libs/bootstrap.min.js
                - assets/js/libs/bootstrap-hover-dropdown.min.js
                - assets/js/plugins/magnific/jquery.magnific-popup.min.js

                - bundles/app/js/frontend/custom.js
                - bundles/rbsoftcart/js/cart.js

            filters:
                - cssrewrite
#                - ?yui_js
