# Assetic Configuration

assetic:
    debug: %kernel.debug%
    use_controller: true
    bundles: [ AppBundle, UsuarioBundle ]
    java: %java_path%
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        lessphp: ~
    assets:
        lesses:
            inputs:
#                - %kernel.root_dir%/../web/assets/bootstrap-2.3.2/less/bootstrap.less
#                - @BricksSiteBundle/Resources/less/*.less
#                - @BricksWikiBundle/Resources/less/*.less
#                - @BricksUserBundle/Resources/less/*.less
#                - @BricksMessageBundle/Resources/less/*.less
            filters: lessphp
        stylesheets:
            inputs:
                #-- Font Awesome CSS --#
                - bundles/app/css/admin/font-awesome.min.css
                #-- Bootstrap CSS --#
                - bundles/app/css/admin/bootstrap.min.css

                - bundles/rbsoftabmgenerador/fileupload/*.css
                #-- App CSS --#>
                - bundles/app/css/admin/mvpready-admin.css
                - bundles/app/css/admin/mvpready-flat.css

                - bundles/rbsoftabmgenerador/fileupload//css/fileinput.min.css

                - @lesses

            filters:
                - cssrewrite
                - ?yui_css
        javascripts_header:
            inputs:
#                - %kernel.root_dir%/../web/assets/js/jquery-ui.js

                - bundles/fosjsrouting/js/router.js
            filters:
                - cssrewrite
                - ?yui_js
        javascripts_footer:
            inputs:
                #-- Bootstrap core JavaScript
                #-- Core JS --#
                - bundles/app/js/admin/libs/jquery-1.10.2.min.js
                - bundles/app/js/admin/libs/bootstrap.min.js

#                Este lo sacamos de aqui porque el assetic modifica el path, es un error.
#                - bundles/rbsoftabmgenerador/fileupload//js/fileinput.js
                ##-- Plugin JS --##
#                <script src="{{ asset('assets/js/plugins/flot/jquery.flot.js') }} "></script>
#                <script src="{{ asset('assets/js/plugins/flot/jquery.flot.tooltip.min.js') }} "></script>
#                <script src="{{ asset('assets./js/plugins/flot/jquery.flot.pie.js') }} "></script>
#                <script src="{{ asset('assets/js/plugins/flot/jquery.flot.resize.js') }} "></script>

                ##-- App JS --##
                - bundles/app/js/admin/mvpready-core.js
                - bundles/app/js/admin/mvpready-admin.js

#                <!-- Plugin JS -->
#                <script src="{{ asset('assets/js/demos/flot/line.js') }} "></script>
#                <script src="{{ asset('assets/js/demos/flot/pie.js') }} "></script>
#                <script src="{{ asset('assets/js/demos/flot/auto.js') }} "></script>
#                <script src="{{ asset('bundles/autogestion/js/jquery.msgbox.min.js') }}" type="text/javascript"></script>
#                <script src="{{ asset('bundles/autogestion/js/notifications.js') }}" type="text/javascript"></script>
#                <script src="http://code.jquery.com/jquery-migrate-1.2.1.js"></script>



            filters:
                - cssrewrite
                - ?yui_js
