app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

_rb_soft_cart:
    resource: "@RBSoftCartBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

