app:
    resource: "@AppBundle/resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"