security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
#            id: fos_user.user_provider.username
            id: fos_user.user_provider.username_email

#    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            context:            site
#            pattern: ^/
#            context: my_security_context
#            form_login:
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#                use_forward: false
#                default_target_path: /profile
#                always_use_default_target_path: true
#            logout:
#                target: homepage
#            anonymous:    true
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: /
                use_referer: true
#                failure_path: http://www.symfony.es

            logout:
                target: homepage
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

          #fronten
        - { path: ^/profile/, roles: [ROLE_USER] }

          #Admin
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/profile, role: [ROLE_ADMIN] }

        - { path: ^/admin/, roles: [ROLE_ADMIN] }
        - { path: ^/admin/usuario, role: ROLE_ADMIN }
#        - { path: ^/, roles: [ROLE_USER] }