parameters:
#    utilidad.example.class: RBSoft\UtilidadBundle\Example

services:
    form.type_extension.help_message:
        class: RBSoft\UtilidadBundle\Form\Extension\HelpMessageTypeExtension
        tags:
          - { name: "form.type_extension", extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    form.type.entity_id:
        class: RBSoft\UtilidadBundle\Form\Type\EntityIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: "form.type", alias: "entity_id" }

#    evento para registrar el usuario en la creacion y edicion de entity que implementan la SecureControl
    usuario.listener.doctrine:
        class: RBSoft\UtilidadBundle\Doctrine\EventListener\UsuarioListener
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.event_listener, event: prePersist,   method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,    method: preUpdate }
