parameters:
#    utilidad.example.class: RBSoft\UtilidadBundle\Example

services:
    form.type_extension.help_message:
        class: RBSoft\UtilidadBundle\Form\Extension\HelpMessageTypeExtension
        tags:
          - { name: "form.type_extension", alias: "form" }

    form.type.entity_id:
        class: RBSoft\UtilidadBundle\Form\Type\EntityIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: "form.type", alias: "entity_id" }