services:
    form.type.metadato_collection:
        class: AppBundle\Form\Type\MetadatoCollectionType
        tags:
          - { name: "form.type", alias: "metadato_collection" }

    form.type.reposicion_items_collection:
        class: AppBundle\Form\Type\ReposicionItemsCollectionType
#        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: "form.type", alias: "reposicion_items_collection" }

    form.type.metadato_filter:
        class: AppBundle\Form\Type\MetadatoFilterType
        tags:
          - { name: "form.type", alias: "metadato_filter" }

    form.type.condicion_iva:
        class: AppBundle\Form\Type\CondicionIvaType
        tags:
          - { name: "form.type", alias: "condicion_iva" }

    form.type.forma_pago:
        class: AppBundle\Form\Type\FormaPagoType
        tags:
          - { name: "form.type", alias: "forma_pago" }

    form.type.metadato_widget:
        class: AppBundle\Form\Type\MetadatoWidgetType
        tags:
          - { name: "form.type", alias: "widget_filter" }

    form.type.app_date_time:
        class: AppBundle\Form\Type\AppDateTimeType
        tags:
          - { name: "form.type", alias: "app_datetime" }

    form.type.my_collection:
        class: AppBundle\Form\Type\MyCollectionType
        tags:
            - { name: "form.type", alias: "my_collection" }
