services:
    form.type.metadato_collection:
        class: AppBundle\Form\Type\MetadatoCollectionType
        tags:
          - { name: "form.type", alias: "metadato_collection" }

    form.type.compra_items_collection:
        class: AppBundle\Form\Type\CompraItemsCollectionType
#        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: "form.type", alias: "compra_items_collection" }

    form.type.metadato_filter:
        class: AppBundle\Form\Type\MetadatoFilterType
        tags:
          - { name: "form.type", alias: "metadato_filter" }

    form.type.metadato_widget:
        class: AppBundle\Form\Type\MetadatoWidgetType
        tags:
          - { name: "form.type", alias: "widget_filter" }

    form.type.app_date_time:
        class: AppBundle\Form\Type\AppDateTimeType
        tags:
          - { name: "form.type", alias: "app_datetime" }

    form.type.my_collection:
        class: AppBundle\Form\Type\MyCollectionType
        tags:
            - { name: "form.type", alias: "my_collection" }
