services:
    categoria.manager:
        class: AppBundle\Manager\CategoriaManager
        arguments:
            - @doctrine.orm.entity_manager
            - @security.token_storage
            - @request_stack

    producto.manager:
        class: AppBundle\Manager\ProductoManager
        arguments:
            - @doctrine.orm.entity_manager
            - @security.token_storage
            - @request_stack

    compra.manager:
        class: AppBundle\Manager\CompraManager
        arguments:
            - @doctrine.orm.entity_manager
            - @security.token_storage
            - @request_stack