
app_frontend:
    prefix:  /
    resource: "@AppBundle/Controller/frontend"
    type:     annotation

app_admin:
    prefix:  /admin/
    resource: '@AppBundle/Controller/admin'
    type:     annotation

#
#frontend:
#    resource: "@AppBundle/Controller/frontend"
#    type:     annotation

#admin_homepage:
#    path:  /admin/
#    defaults:  { _controller: UsuarioBundle:Usuario:Index}

# Admin
