
app_frontend:
    prefix:  /
    resource: "@AppBundle/Controller"


admin_homepage:
    path:  /admin/
#    resource: "@UsuarioBundle/Controller"

    defaults:  { _controller: UsuarioBundle:Usuario:Index}

