services:
    categoria.listener.doctrine:
        class: AppBundle\EventListener\CategoriaListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist,   method: prePersist }
            - { name: doctrine.event_listener, event: postPersist,  method: postPersist }
            - { name: doctrine.event_listener, event: preUpdate,    method: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate,   method: postUpdate }

    form.type.metadato_collection:
        class: AppBundle\Form\Type\MetadatoCollectionType
        tags:
          - { name: "form.type", alias: "metadato_collection" }

    menu.service:
        class: AppBundle\Servicios\MenuService
        arguments: [@service_container]

    app.cache_warmer:
        class: AppBundle\Servicios\CacheWarmer\AppCacheWarmer
        tags:
            - { name: kernel.cache_warmer }

