app_frontend:
    prefix:  /
    resource: "@AppBundle/Controller/frontend"

app_admin:
    prefix:  /admin/
    resource: "@AppBundle/Controller/admin"

admin_homepage:
    path:  /admin/
    defaults:  { _controller: UsuarioBundle:Usuario:Index}

