<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
    public function selectOrdenTree()
    {
        $qb = $this->createQueryBuilder("q")
            ->where('q.level < :level')
            ->orderBy('q.root, q.level', 'ASC')
            ->setParameter('level', 2);
        return $qb;

    }
}
