<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContenidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenidoRepository extends EntityRepository
{
    public function getContenido(){

        return $this->_em->createQuery("
            SELECT c
            FROM AppBundle:Contenido c
            WHERE c.activo = 1
            ORDER BY c.orden ASC
        ")->execute()
        ;
    }

}
