<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    public function ListAll()
    {
        $qb = $this->createQueryBuilder("q")->orderBy('q.createdAt', 'ASC');
        return $qb;

    }

    public function getUltimos()
    {
        $em = $this->getEntityManager();

        $consulta = $em->createQuery('
            SELECT p, c
            FROM AppBundle:Producto p JOIN  p.categoria c
            WHERE p.stock >0
            ORDER BY p.createdAt DESC
        ');

        $consulta->setMaxResults(4);
        $consulta->useResultCache(true, 600);

        return $consulta->getResult();
    }




    public function getProductos(Categoria $cat){

    }
}
