_usuario_admin:
    prefix:  /admin
    resource: "@UsuarioBundle/Controller"

# usuario
usuario_login:
    path: /login
    defaults: { _controller: UsuarioBundle:Security:login}

usuario_login_check:
    path: /login_check

usuario_logout:
    path: /logout

# Admin
admin_login:
    pattern:  /admin/login
    defaults: { _controller: UsuarioBundle:Security:login }

admin_login_check:
    pattern:  /admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

admin_logout:
    pattern:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }