parameters:
#    usuario.example.class: RBSoft\UsuarioBundle\Example

services:
#    usuario.example:
#        class: %usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    usuario.listener.doctrine:
        class: RBSoft\UsuarioBundle\EventListener\UsuarioListener
        arguments: [@security.token_storage]
        tags:
            - { name: doctrine.event_listener, event: prePersist,   method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,    method: preUpdate }