parameters:
#    usuario.example.class: RBSoft\UsuarioBundle\Example

services:
    rbsoft.profile.form.type:
        class: RBSoft\UsuarioBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: usuario_profile }
    rbsoft.registration.form.type:
        class: RBSoft\UsuarioBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: usuario_registration }

    usuario.listener.doctrine:
        class: RBSoft\UsuarioBundle\Doctrine\EventListener\UsuarioListener
        arguments: [@security.token_storage]
        tags:
            - { name: doctrine.event_listener, event: prePersist,   method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,    method: preUpdate }