<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MetadatoProducto extends \AppBundle\Entity\MetadatoProducto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'predeterminado', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'filtrable', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'requerido', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'widget', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'orden', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'listaValores', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'categoria'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'predeterminado', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'filtrable', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'requerido', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'widget', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'orden', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'listaValores', '' . "\0" . 'AppBundle\\Entity\\MetadatoProducto' . "\0" . 'categoria'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MetadatoProducto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiltrable($filtrable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiltrable', [$filtrable]);

        return parent::setFiltrable($filtrable);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiltrable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiltrable', []);

        return parent::getFiltrable();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidget($widget)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidget', [$widget]);

        return parent::setWidget($widget);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidget()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidget', []);

        return parent::getWidget();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequerido($requerido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequerido', [$requerido]);

        return parent::setRequerido($requerido);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequerido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequerido', []);

        return parent::getRequerido();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrden($orden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrden', [$orden]);

        return parent::setOrden($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrden', []);

        return parent::getOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function setListaValores($listaValores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListaValores', [$listaValores]);

        return parent::setListaValores($listaValores);
    }

    /**
     * {@inheritDoc}
     */
    public function getListaValores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListaValores', []);

        return parent::getListaValores();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria(\AppBundle\Entity\Categoria $categoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', [$categoria]);

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', []);

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setPredeterminado($predeterminado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPredeterminado', [$predeterminado]);

        return parent::setPredeterminado($predeterminado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPredeterminado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPredeterminado', []);

        return parent::getPredeterminado();
    }

    /**
     * {@inheritDoc}
     */
    public function isEmpty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEmpty', []);

        return parent::isEmpty();
    }

}
