<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ReposicionItem extends \AppBundle\Entity\ReposicionItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'reposicion', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'cantidad', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'precioUnitario', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'producto', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'productoNombre', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'productoCodigo'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'reposicion', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'cantidad', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'precioUnitario', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'producto', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'productoNombre', '' . "\0" . 'AppBundle\\Entity\\ReposicionItem' . "\0" . 'productoCodigo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ReposicionItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioUnitario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioUnitario', []);

        return parent::getPrecioUnitario();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioUnitario($precio_unitario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioUnitario', [$precio_unitario]);

        return parent::setPrecioUnitario($precio_unitario);
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidad($cantidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidad', [$cantidad]);

        return parent::setCantidad($cantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidad', []);

        return parent::getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setReposicion(\AppBundle\Entity\Reposicion $reposicion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReposicion', [$reposicion]);

        return parent::setReposicion($reposicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getReposicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReposicion', []);

        return parent::getReposicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setProducto(\AppBundle\Entity\Producto $producto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProducto', [$producto]);

        return parent::setProducto($producto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducto', []);

        return parent::getProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductoCodigo($p)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductoCodigo', [$p]);

        return parent::setProductoCodigo($p);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductoCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductoCodigo', []);

        return parent::getProductoCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductoNombre($p)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductoNombre', [$p]);

        return parent::setProductoNombre($p);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductoNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductoNombre', []);

        return parent::getProductoNombre();
    }

}
