<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categoria extends \AppBundle\Entity\Categoria implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'orden', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'level', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'root', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'children', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'parent', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'visible', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'metadatos', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'imagen', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'usuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'orden', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'level', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'root', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'children', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'parent', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'visible', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'metadatos', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'imagen', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Categoria' . "\0" . 'usuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Categoria $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getNodeNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNodeNombre', []);

        return parent::getNodeNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrden($orden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrden', [$orden]);

        return parent::setOrden($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrden', []);

        return parent::getOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevel($level)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevel', [$level]);

        return parent::setLevel($level);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', []);

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\RBSoft\UsuarioBundle\Entity\Usuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoot($root)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoot', [$root]);

        return parent::setRoot($root);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoot', []);

        return parent::getRoot();
    }

    /**
     * {@inheritDoc}
     */
    public function addChild(\AppBundle\Entity\Categoria $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChild', [$children]);

        return parent::addChild($children);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChild(\AppBundle\Entity\Categoria $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChild', [$children]);

        return parent::removeChild($children);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildren', []);

        return parent::getChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\AppBundle\Entity\Categoria $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible($visible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', [$visible]);

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', []);

        return parent::getVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function addMetadato(\AppBundle\Entity\MetadatoProducto $metadatos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMetadato', [$metadatos]);

        return parent::addMetadato($metadatos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMetadato(\AppBundle\Entity\MetadatoProducto $metadatos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMetadato', [$metadatos]);

        return parent::removeMetadato($metadatos);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetadatos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetadatos', []);

        return parent::getMetadatos();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen($imagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', [$imagen]);

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function upload($dir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', [$dir]);

        return parent::upload($dir);
    }

    /**
     * {@inheritDoc}
     */
    public function getStrAscentendeCategoria(\AppBundle\Entity\Categoria $cat = NULL, $separador = ' / ')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStrAscentendeCategoria', [$cat, $separador]);

        return parent::getStrAscentendeCategoria($cat, $separador);
    }

}
