<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cliente extends \AppBundle\Entity\Cliente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'apellido', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'movil', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'fax', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delNombre', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delDir1', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delDir2', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delCiudad', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delCodPostal', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delPais', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delPcia', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'usuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'apellido', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'movil', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'fax', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delNombre', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delDir1', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delDir2', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delCiudad', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delCodPostal', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delPais', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'delPcia', '' . "\0" . 'AppBundle\\Entity\\Cliente' . "\0" . 'usuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cliente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', [$apellido]);

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', []);

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setMovil($movil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMovil', [$movil]);

        return parent::setMovil($movil);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovil', []);

        return parent::getMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$fax]);

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelNombre($delNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelNombre', [$delNombre]);

        return parent::setDelNombre($delNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelNombre', []);

        return parent::getDelNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelDir1($delDir1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelDir1', [$delDir1]);

        return parent::setDelDir1($delDir1);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelDir1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelDir1', []);

        return parent::getDelDir1();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelDir2($delDir2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelDir2', [$delDir2]);

        return parent::setDelDir2($delDir2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelDir2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelDir2', []);

        return parent::getDelDir2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad($ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', [$ciudad]);

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', []);

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelCodpostal($delCodpostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelCodpostal', [$delCodpostal]);

        return parent::setDelCodpostal($delCodpostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelCodpostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelCodpostal', []);

        return parent::getDelCodpostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelPais($delPais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelPais', [$delPais]);

        return parent::setDelPais($delPais);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelPais', []);

        return parent::getDelPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelPcia($delPcia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelPcia', [$delPcia]);

        return parent::setDelPcia($delPcia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelPcia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelPcia', []);

        return parent::getDelPcia();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelCiudad($delCiudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelCiudad', [$delCiudad]);

        return parent::setDelCiudad($delCiudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelCiudad', []);

        return parent::getDelCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\RBSoft\UsuarioBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

}
