<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reposicion extends \AppBundle\Entity\Reposicion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'proveedor', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'fechaReposicion', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'fechaAlta', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'facturaNumero', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'items'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'proveedor', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'fechaReposicion', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'fechaAlta', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'facturaNumero', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Reposicion' . "\0" . 'items'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reposicion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function PrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'PrePersist', []);

        return parent::PrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaReposicion($fechaReposicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaReposicion', [$fechaReposicion]);

        return parent::setFechaReposicion($fechaReposicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaReposicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaReposicion', []);

        return parent::getFechaReposicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', [$fechaAlta]);

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacturaNumero($facturaNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacturaNumero', [$facturaNumero]);

        return parent::setFacturaNumero($facturaNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacturaNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacturaNumero', []);

        return parent::getFacturaNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setProveedor(\AppBundle\Entity\Proveedor $proveedor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProveedor', [$proveedor]);

        return parent::setProveedor($proveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProveedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProveedor', []);

        return parent::getProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\RBSoft\UsuarioBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function addItem(\AppBundle\Entity\ReposicionItem $item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItem', [$item]);

        return parent::addItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItem(\AppBundle\Entity\ReposicionItem $item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItem', [$item]);

        return parent::removeItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function getItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', []);

        return parent::getItems();
    }

}
