<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \AppBundle\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'precio', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'costo', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'iva', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'imagenes', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'bonificaciones', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'categoria', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'extencion', 'createdAt', 'updatedAt', 'stock', 'limiteStock'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'precio', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'costo', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'iva', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'imagenes', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'bonificaciones', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'categoria', '' . "\0" . 'AppBundle\\Entity\\Producto' . "\0" . 'extencion', 'createdAt', 'updatedAt', 'stock', 'limiteStock'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Producto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock($stock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', [$stock]);

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', []);

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setLimiteStock($limiteStock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLimiteStock', [$limiteStock]);

        return parent::setLimiteStock($limiteStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getLimiteStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLimiteStock', []);

        return parent::getLimiteStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\RBSoft\UsuarioBundle\Entity\Usuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', [$precio]);

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', []);

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCosto($costo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCosto', [$costo]);

        return parent::setCosto($costo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCosto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCosto', []);

        return parent::getCosto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIva($iva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIva', [$iva]);

        return parent::setIva($iva);
    }

    /**
     * {@inheritDoc}
     */
    public function getIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIva', []);

        return parent::getIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function addImagene(\AppBundle\Entity\ProductoImagen $imagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImagene', [$imagen]);

        return parent::addImagene($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImagene(\AppBundle\Entity\ProductoImagen $imagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImagene', [$imagen]);

        return parent::removeImagene($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagenes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagenes', []);

        return parent::getImagenes();
    }

    /**
     * {@inheritDoc}
     */
    public function addBonificacione(\AppBundle\Entity\ProductoBonificacion $bonificaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBonificacione', [$bonificaciones]);

        return parent::addBonificacione($bonificaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBonificacione(\AppBundle\Entity\ProductoBonificacion $bonificaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBonificacione', [$bonificaciones]);

        return parent::removeBonificacione($bonificaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getBonificaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBonificaciones', []);

        return parent::getBonificaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria(\AppBundle\Entity\Categoria $categoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', [$categoria]);

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', []);

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function getImagenActiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagenActiva', []);

        return parent::getImagenActiva();
    }

    /**
     * {@inheritDoc}
     */
    public function addExtencion(\AppBundle\Entity\ProductoExtension $extencion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExtencion', [$extencion]);

        return parent::addExtencion($extencion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExtencion(\AppBundle\Entity\ProductoExtension $extencion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExtencion', [$extencion]);

        return parent::removeExtencion($extencion);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtencion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtencion', []);

        return parent::getExtencion();
    }

    /**
     * {@inheritDoc}
     */
    public function procesarMetadato(\AppBundle\Entity\MetadatoProducto $metadato, $valor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'procesarMetadato', [$metadato, $valor]);

        return parent::procesarMetadato($metadato, $valor);
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', []);

        return parent::preUpload();
    }

}
