<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proveedor extends \AppBundle\Entity\Proveedor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'razon_social', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'nombre_fantasia', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'cuit', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'domicilio', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'localidad', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'codigo_postal', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'pagina_web', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'fax', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto_telefono', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto_int', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto_fax', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto_movil', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto_email', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'moneda', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'limite_credito', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'tipo_pago', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'descuento', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'cond_iva', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'n_cuenta', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'observacion'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'razon_social', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'nombre_fantasia', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'cuit', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'domicilio', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'localidad', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'codigo_postal', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'pagina_web', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'fax', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto_telefono', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto_int', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto_fax', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto_movil', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'contacto_email', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'moneda', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'limite_credito', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'tipo_pago', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'descuento', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'cond_iva', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'n_cuenta', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Proveedor' . "\0" . 'observacion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proveedor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\RBSoft\UsuarioBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazonSocial($razonSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazonSocial', [$razonSocial]);

        return parent::setRazonSocial($razonSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazonSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazonSocial', []);

        return parent::getRazonSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreFantasia($nombreFantasia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreFantasia', [$nombreFantasia]);

        return parent::setNombreFantasia($nombreFantasia);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreFantasia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreFantasia', []);

        return parent::getNombreFantasia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCuit($cuit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCuit', [$cuit]);

        return parent::setCuit($cuit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCuit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuit', []);

        return parent::getCuit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicilio($domicilio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicilio', [$domicilio]);

        return parent::setDomicilio($domicilio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilio', []);

        return parent::getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoPostal($codigoPostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoPostal', [$codigoPostal]);

        return parent::setCodigoPostal($codigoPostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoPostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoPostal', []);

        return parent::getCodigoPostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaginaWeb($paginaWeb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaginaWeb', [$paginaWeb]);

        return parent::setPaginaWeb($paginaWeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaginaWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaginaWeb', []);

        return parent::getPaginaWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$fax]);

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setContacto($contacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContacto', [$contacto]);

        return parent::setContacto($contacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacto', []);

        return parent::getContacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactoTelefono($contactoTelefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactoTelefono', [$contactoTelefono]);

        return parent::setContactoTelefono($contactoTelefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactoTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactoTelefono', []);

        return parent::getContactoTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactoInt($contactoInt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactoInt', [$contactoInt]);

        return parent::setContactoInt($contactoInt);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactoInt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactoInt', []);

        return parent::getContactoInt();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactoFax($contactoFax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactoFax', [$contactoFax]);

        return parent::setContactoFax($contactoFax);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactoFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactoFax', []);

        return parent::getContactoFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactoMovil($contactoMovil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactoMovil', [$contactoMovil]);

        return parent::setContactoMovil($contactoMovil);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactoMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactoMovil', []);

        return parent::getContactoMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactoEmail($contactoEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactoEmail', [$contactoEmail]);

        return parent::setContactoEmail($contactoEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactoEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactoEmail', []);

        return parent::getContactoEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneda($moneda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneda', [$moneda]);

        return parent::setMoneda($moneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneda', []);

        return parent::getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setLimiteCredito($limiteCredito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLimiteCredito', [$limiteCredito]);

        return parent::setLimiteCredito($limiteCredito);
    }

    /**
     * {@inheritDoc}
     */
    public function getLimiteCredito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLimiteCredito', []);

        return parent::getLimiteCredito();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoPago($tipoPago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoPago', [$tipoPago]);

        return parent::setTipoPago($tipoPago);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoPago', []);

        return parent::getTipoPago();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescuento($descuento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescuento', [$descuento]);

        return parent::setDescuento($descuento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescuento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescuento', []);

        return parent::getDescuento();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondIva($condIva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondIva', [$condIva]);

        return parent::setCondIva($condIva);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondIva', []);

        return parent::getCondIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setNCuenta($nCuenta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNCuenta', [$nCuenta]);

        return parent::setNCuenta($nCuenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getNCuenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNCuenta', []);

        return parent::getNCuenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad(\RBSoft\UtilidadBundle\Entity\Localidad $localidad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

}
