<?php

namespace Proxies\__CG__\RBSoft\CartBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Orden extends \RBSoft\CartBundle\Entity\Orden implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'id', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'estado', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'estadoFecha', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'importeSinIva', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'importeConIva', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'createdAt', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'upatedAt', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'factura', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'item'];
        }

        return ['__isInitialized__', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'id', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'estado', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'estadoFecha', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'importeSinIva', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'importeConIva', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'createdAt', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'upatedAt', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'factura', '' . "\0" . 'RBSoft\\CartBundle\\Entity\\Orden' . "\0" . 'item'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Orden $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoFecha($estadoFecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoFecha', [$estadoFecha]);

        return parent::setEstadoFecha($estadoFecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoFecha', []);

        return parent::getEstadoFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporteSinIva($importeSinIva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporteSinIva', [$importeSinIva]);

        return parent::setImporteSinIva($importeSinIva);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporteSinIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporteSinIva', []);

        return parent::getImporteSinIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setImporteConIva($importeConIva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImporteConIva', [$importeConIva]);

        return parent::setImporteConIva($importeConIva);
    }

    /**
     * {@inheritDoc}
     */
    public function getImporteConIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImporteConIva', []);

        return parent::getImporteConIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpatedAt($upatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpatedAt', [$upatedAt]);

        return parent::setUpatedAt($upatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpatedAt', []);

        return parent::getUpatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setFactura($factura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactura', [$factura]);

        return parent::setFactura($factura);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactura', []);

        return parent::getFactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setItem($item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItem', [$item]);

        return parent::setItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function getItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItem', []);

        return parent::getItem();
    }

}
